### ISSUE TITLE
Patch from debian install core.json

### ISSUE THREAD

**Issue by bastien-roucaries** [inspect-js/is-core-module#9]
Hi,

Could you apply the following patch
```
Install core.json

core.json should be installed

Forwarded: 

Index: node-resolve/is-core-module/package.json
===================================================================
--- node-resolve.orig/is-core-module/package.json
+++ node-resolve/is-core-module/package.json
@@ -3,6 +3,7 @@
 	"version": "2.6.0",
 	"description": "Is this specifier a node.js core module?",
 	"main": "index.js",
+        "files" : ["./core.json"],
 	"exports": {
 		".": [
 			{
```

**Comment by ljharb** [comment]
I have no idea what you're asking for.

I absolutely will not ever use the `files` array; it's very dangerous, and your suggested patch would make the entire module not requireable and break many millions of users a week.

`npm install is-core-module` already includes `core.json`. This module, like almost every npm module, is exclusively distributed from npm. Installing it from debian is a category error, and you should never expect anything to work when you do that.

**Comment by bastien-roucaries** [comment]
Debian pull from github and your script workarround the missing files array. So I suggested this patch. Note that index.js and package.json are always pulled

**Comment by ljharb** [comment]
Debian should not do that, they should pull from npm - but also, a) the "files" array is not required in npm packages, so if debian requires it they're doing it wrong, and b) `index.js` is *not* always pulled in npm packages, so that is also a bug.

The only files list they should be using is `npm pack --dry-run`, and this would have to be ran after a build process - so they should only be using the tarball from the npm registry, and never github.

There doesn't seem to be anything to change here.
